/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/full_adder_opt.sv:2.1-15.10" *)
module full_adder_opt(a, b, cin, sum, cout);
  (* src = "rtl/full_adder_opt.sv:3.11-3.12" *)
  input a;
  wire a;
  (* src = "rtl/full_adder_opt.sv:3.14-3.15" *)
  input b;
  wire b;
  (* src = "rtl/full_adder_opt.sv:3.17-3.20" *)
  input cin;
  wire cin;
  (* src = "rtl/full_adder_opt.sv:4.17-4.21" *)
  output cout;
  wire cout;
  (* src = "rtl/full_adder_opt.sv:4.12-4.15" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__maj3_1 _0_ (
    .A(a),
    .B(b),
    .C(cin),
    .X(cout)
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(a),
    .B(b),
    .C(cin),
    .X(sum)
  );
endmodule
