/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/full_adder_naive.sv:2.1-14.10" *)
module full_adder_naive(a, b, cin, sum, cout);
  (* src = "rtl/full_adder_naive.sv:3.11-3.12" *)
  input a;
  wire a;
  (* src = "rtl/full_adder_naive.sv:3.14-3.15" *)
  input b;
  wire b;
  (* src = "rtl/full_adder_naive.sv:7.10-7.12" *)
  wire c1;
  (* src = "rtl/full_adder_naive.sv:7.14-7.16" *)
  wire c2;
  (* src = "rtl/full_adder_naive.sv:3.17-3.20" *)
  input cin;
  wire cin;
  (* src = "rtl/full_adder_naive.sv:4.17-4.21" *)
  output cout;
  wire cout;
  (* src = "rtl/full_adder_naive.sv:7.6-7.8" *)
  wire s1;
  (* src = "rtl/full_adder_naive.sv:4.12-4.15" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(c1),
    .SLEEP(c2),
    .X(cout)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/full_adder_naive.sv:10.12-10.45" *)
  half_adder ha0 (
    .c(c1),
    .s(s1),
    .x(a),
    .y(b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/full_adder_naive.sv:11.12-11.49" *)
  half_adder ha1 (
    .c(c2),
    .s(sum),
    .x(s1),
    .y(cin)
  );
endmodule

(* src = "rtl/half_adder.sv:1.1-4.10" *)
module half_adder(x, y, s, c);
  (* src = "rtl/half_adder.sv:1.53-1.54" *)
  output c;
  wire c;
  (* src = "rtl/half_adder.sv:1.50-1.51" *)
  output s;
  wire s;
  (* src = "rtl/half_adder.sv:1.31-1.32" *)
  input x;
  wire x;
  (* src = "rtl/half_adder.sv:1.34-1.35" *)
  input y;
  wire y;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(x),
    .B(y),
    .X(c)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(x),
    .B(y),
    .X(s)
  );
endmodule
